### ISSUE TITLE
How does this compare to the current Maya aur package?

### ISSUE THREAD

**Issue by IcyAlmond** [MyHCel/Maya-For-Arch#4]

**Comment by MyHCel** [comment]
I'm not aware of the current status of the Maya AUR package.

I created this project because just installing the package did not make Maya work (I don't know if it does now), there are some fixes that need to be applied, such as linking libraries, etc. This is basically the result of many workarounds I found on the Internet.

Also, the AUR package only provides you with the latest version of Maya, while this project let's you install the previous version "2020".
